export const seoCourseArtworkImages: Record<string, string> = {
  "meta-pavadinimai": "/seo-lessons/meta-pavadinimai-v2.webp",
  "meta-aprasymai": "/seo-lessons/meta-aprasymai-v2.webp",
  "url-adresu-struktura": "/seo-lessons/url-struktura-v2.webp",
  "svetaines-narsymas": "/seo-lessons/svetaines-narsymas-v2.webp",
  "kokybiskas-turinys": "/seo-lessons/kokybiskas-turinys-v2.webp",
  "anchor-tekstai": "/seo-lessons/anchor-tekstai-v2.webp",
  "paveiksleliu-seo": "/seo-lessons/paveiksleliu-seo-v2.webp",
  "heading-tags": "/seo-lessons/heading-tags-v2.webp",
  "robots-txt": "/seo-lessons/robots-txt-v2.webp",
  "nofollow-nuorodos": "/seo-lessons/nofollow-nuorodos-v2.webp",
  "mobilioji-versija": "/seo-lessons/mobilioji-versija-v2.webp",
  "mobilus-narsymas": "/seo-lessons/mobilus-narsymas-v2.webp",
  "svetaines-reklama": "/seo-lessons/svetaines-reklama-v2.webp",
  "webmaster-irankiai": "/seo-lessons/webmaster-irankiai-v2.webp",
  "google-ai-overviews": "/seo-lessons/ai-overviews-v2.webp",
  "position-zero": "/seo-lessons/position-zero-v2.webp",
  "atgaliniu-nuorodu-kokybe": "/seo-lessons/backlink-kokybe-v2.webp",
  "seo-konkurentu-analize": "/seo-lessons/konkurentu-analize-v2.webp",
  "vidinis-seo-klasteriai": "/seo-lessons/vidinis-seo-v2.webp",
  "kodel-manes-neranda-google": "/seo-lessons/kodel-neranda-google-v2.webp",
};
